//! Detection for ADD COLUMN with GENERATED ... AS IDENTITY.
//!
//! This check identifies `ALTER TABLE` statements that add columns with
//! `GENERATED BY DEFAULT AS IDENTITY` or `GENERATED ALWAYS AS IDENTITY`,
//! which trigger a full table rewrite.
//!
//! Adding an identity column to an existing table requires Postgres to:
//! 1. Create a new sequence
//! 2. Rewrite the entire table to populate the sequence values for existing rows
//! 3. Update all indexes
//!
//! The PG 11 constant-default optimization does not apply because `nextval()` is
//! volatile. PostgreSQL's own documentation explicitly lists identity columns as
//! triggering a full rewrite.
//!
//! This operation acquires an ACCESS EXCLUSIVE lock, blocking all operations.
//! Duration depends on table size and number of indexes.

use crate::checks::pg_helpers::{
    NodeEnum, alter_table_cmds, cmd_def_as_column_def, column_type_name, is_identity_pattern,
};
use crate::checks::{Check, CheckDoc, Config, MigrationContext, impl_check_doc};
use crate::violation::Violation;

pub struct AddIdentityColumnCheck;
impl_check_doc!(AddIdentityColumnCheck, "add-identity-column");

impl Check for AddIdentityColumnCheck {
    fn check(&self, node: &NodeEnum, _config: &Config, _ctx: &MigrationContext) -> Vec<Violation> {
        let Some((table_name, cmds)) = alter_table_cmds(node) else {
            return vec![];
        };

        cmds.iter()
            .filter_map(|cmd| {
                let col = cmd_def_as_column_def(cmd)?;

                if !is_identity_pattern(col) {
                    return None;
                }

                let column_name = &col.colname;
                let type_name = column_type_name(col);
                let sql_type = match type_name.as_str() {
                    "int8" => "BIGINT",
                    "int4" => "INTEGER",
                    "int2" => "SMALLINT",
                    other => other,
                };

                Some(Violation::new(
                    "ADD COLUMN with IDENTITY",
                    format!(
                        "Adding column '{column_name}' with GENERATED AS IDENTITY on table '{table_name}' requires a full table rewrite to populate sequence values for existing rows, \
                        which acquires an ACCESS EXCLUSIVE lock and blocks all operations. Duration depends on table size and number of indexes."
                    ),
                    format!(r"1. Create a sequence:
   CREATE SEQUENCE {table_name}_{column_name}_seq;

2. Add the column WITHOUT default (fast, no rewrite):
   ALTER TABLE {table_name} ADD COLUMN {column_name} {sql_type};

3. Backfill existing rows in batches (outside migration):
   UPDATE {table_name} SET {column_name} = nextval('{table_name}_{column_name}_seq') WHERE {column_name} IS NULL;

4. Set default for future inserts only:
   ALTER TABLE {table_name} ALTER COLUMN {column_name} SET DEFAULT nextval('{table_name}_{column_name}_seq');

5. Set NOT NULL if needed (Postgres 11+: safe if all values present):
   ALTER TABLE {table_name} ALTER COLUMN {column_name} SET NOT NULL;

6. Set sequence ownership:
   ALTER SEQUENCE {table_name}_{column_name}_seq OWNED BY {table_name}.{column_name};"
                    ),
                ))
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{assert_allows, assert_detects_n_violations, assert_detects_violation};

    #[test]
    fn test_detects_add_column_with_generated_by_default() {
        assert_detects_violation!(
            AddIdentityColumnCheck,
            "ALTER TABLE users ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;",
            "ADD COLUMN with IDENTITY"
        );
    }

    #[test]
    fn test_detects_add_column_with_generated_always() {
        assert_detects_violation!(
            AddIdentityColumnCheck,
            "ALTER TABLE users ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY;",
            "ADD COLUMN with IDENTITY"
        );
    }

    #[test]
    fn test_detects_integer_identity() {
        assert_detects_violation!(
            AddIdentityColumnCheck,
            "ALTER TABLE orders ADD COLUMN seq INTEGER GENERATED BY DEFAULT AS IDENTITY;",
            "ADD COLUMN with IDENTITY"
        );
    }

    #[test]
    fn test_detects_smallint_identity() {
        assert_detects_violation!(
            AddIdentityColumnCheck,
            "ALTER TABLE orders ADD COLUMN seq SMALLINT GENERATED BY DEFAULT AS IDENTITY;",
            "ADD COLUMN with IDENTITY"
        );
    }

    #[test]
    fn test_detects_only_identity_column_in_multi_column_alter() {
        assert_detects_n_violations!(
            AddIdentityColumnCheck,
            "ALTER TABLE orders ADD COLUMN seq BIGINT GENERATED ALWAYS AS IDENTITY, ADD COLUMN name TEXT;",
            1,
            "ADD COLUMN with IDENTITY"
        );
    }

    #[test]
    fn test_detects_non_integer_type_identity() {
        assert_detects_violation!(
            AddIdentityColumnCheck,
            "ALTER TABLE orders ADD COLUMN seq NUMERIC GENERATED BY DEFAULT AS IDENTITY;",
            "ADD COLUMN with IDENTITY"
        );
    }

    #[test]
    fn test_allows_add_column_with_integer() {
        assert_allows!(
            AddIdentityColumnCheck,
            "ALTER TABLE users ADD COLUMN count INTEGER;"
        );
    }

    #[test]
    fn test_allows_create_table_with_identity() {
        assert_allows!(
            AddIdentityColumnCheck,
            "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);"
        );
    }

    #[test]
    fn test_ignores_other_statements() {
        assert_allows!(
            AddIdentityColumnCheck,
            "CREATE INDEX idx_users_email ON users(email);"
        );
    }
}
