[book]
title = "diesel-guard"
authors = ["Alex Yarotsky"]
language = "en"
src = "src"

[output.html]
site-url = "/diesel-guard/"
git-repository-url = "https://github.com/ayarotsky/diesel-guard"
edit-url-template = "https://github.com/ayarotsky/diesel-guard/edit/main/docs/{path}"
default-theme = "light"
preferred-dark-theme = "coal"

[output.html.redirect]
"/checks/add_foreign_key.html" = "/checks/add-foreign-key.html"
"/checks/adding-index.html" = "/checks/add-index.html"
"/checks/adding-unique-constraint.html" = "/checks/add-unique-constraint.html"
"/checks/changing-column-type.html" = "/checks/alter-column-type.html"
"/checks/char-field.html" = "/checks/char-type.html"
"/checks/creating-extension.html" = "/checks/create-extension.html"
"/checks/dropping-column.html" = "/checks/drop-column.html"
"/checks/dropping-constraint.html" = "/checks/drop-constraint.html"
"/checks/dropping-database.html" = "/checks/drop-database.html"
"/checks/dropping-index.html" = "/checks/drop-index.html"
"/checks/dropping-primary-key.html" = "/checks/drop-primary-key.html"
"/checks/dropping-table.html" = "/checks/drop-table.html"
"/checks/json-field.html" = "/checks/add-json-column.html"
"/checks/multiple-column-index.html" = "/checks/wide-index.html"
"/checks/renaming-column.html" = "/checks/rename-column.html"
"/checks/renaming-schema.html" = "/checks/rename-schema.html"
"/checks/renaming-table.html" = "/checks/rename-table.html"
"/checks/reindexing.html" = "/checks/reindex.html"
"/checks/serial-primary-key.html" = "/checks/add-serial-column.html"
"/checks/timestamp-field.html" = "/checks/timestamp-type.html"
"/checks/truncating-table.html" = "/checks/truncate-table.html"
